/**
 * PERFECT.PERMUTATION.API.YML
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * PerfectPermutationMetaInfo
 */
export interface PerfectPermutationMetaInfo { 
    numberOfElements: number;
    status: string;
    numberOfElementsWithMoreThanOneMatch: number;
    maxNumberOfMatchings: number;
    fillAlgorithm: string;
    numberOfCycles: number;
    maxNumberOfGroups: number;
    minNumberOfGroups: number;
    maxElementsInLargestGroup: number;
    minElementsInSmallestGroup: number;
}

